### ISSUE TITLE
What is the function of core.min.js polyfill?

### ISSUE THREAD

**Issue by kristianmandrup** [fchristant/ce-hw#2]
I can't see it being used anywhere...!? Is this a leftover? 

PS: Would love to see this repo working with Webpack 2 as well :)

**Comment by fchristant** [comment]
hi @kristianmandrup Yes, I do believe it is a leftover. I tried to get browser support with IE11 and IE10 included, which requires some ES6 polyfills, for example for Promises. 

Also wanted to let you know that I won't be putting much effort into this repo as I'm currently working on some other stuff (check out my recent articles). So you are very much invited to spin this repo any way you see fit. I'd love to see it become more useful as there really are so few custom elements examples out there.

**Comment by kristianmandrup** [comment]
Hi @fchristant Thanks :) I see your point regarding `core-js` now. I plan to add a webpack 2.2 configuration for now. Then I will use the setup for a Cycle.js app (with RxJS). Perfect duo really.
I will check your other recent articles as well... Haven't even read through your CE article yet!

**Comment by fchristant** [comment]
@kristianmandrup Thanks for picking this up and improving it, really appreciated.
And yes, I tend to write very loooooong articles...that nobody reads :)

**Comment by kristianmandrup** [comment]
Nobody reads!? Wow! The most mind blowing posts I've seen in a very long time!!!
I've also been "web coding" since before the `.com` bubble, and I've yet to find a development "frame" I like. 

Been "skinny dipping" in all the popular frameworks around but never really found them to my liking. *Travel light* is what experience teaches you... *Technical debt* is a **KILLER**

Why I love your general (sceptical) approach so much! 

Would love to get more in touch with you and share ideas...
I'd totally base my future developments on your work, since it looks like the closest match to what 
I've been looking for all along... Striving for a service/component based experience on both front and backend! Reuse all the way!

All the frameworks today are trying to solve the problems of ~2015, but we are already in a VERY different world! Thanks for highlighting! 

Cheers!

**Comment by fchristant** [comment]
@kristianmandrup Thanks for the kind words. Mind you, I'm bad at building the audience. I believe the writing would be interesting for more people, but that's OK, glad you found it.

You may also enjoy my recent experiments with simple ES6 modules and SystemJS, with zero bundling:
https://ferdychristant.com/es6-modules-as-components-32a7b81fe9be?source=collection_home---5------2----------
https://ferdychristant.com/components-on-the-cheap-2df56958b4d7?source=collection_home---5------1----------

Also pretty lengthy, but if you're interested in component-based development as light as possible, without a framework, those may be of interest.

**Comment by kristianmandrup** [comment]
Yes, I already read all your Web dev articles for 2017.

Now I'm checking out [Shadow DOM](https://www.webcomponents.org/community/articles/introduction-to-shadow-dom) and [Template element](http://blog.teamtreehouse.com/creating-reusable-markup-with-the-html-template-element) again.

Would be interesting to do simple Component (Shadow DOM) templating via [doT](http://olado.github.io/doT/index.html)

Initially thought it was too much trouble "rolling my own", but your posts opened my eyes to the simplicity! 

Looks so simple and provides so much freedom instead of being constrained by someones preferences. I liked the simplicity of Vue.js, but still a lot of cost/benefit tradeoffs. Like you, I prefer to travel light (backpacker).

**Comment by kristianmandrup** [comment]
I've been trying to get Babel transpilation working as well for true SSR, but hitting some [issues](https://github.com/github/babel-plugin-transform-custom-element-classes/issues/5)

Any ideas what I could be missing? Did you have success with this?

I see some other devs had [similar issues](https://github.com/ceolter/ag-grid-react/issues/24)

[ce-cycle](https://github.com/kristianmandrup/ce-cycle)

**Comment by fchristant** [comment]
Nice follow-ups you got going on, very interesting, and thank you kindly for the credits you include. 
As for the particular issue you're having, I'm afraid I'm not familiar with cycle.js specifically so it will be hard to put my finger on anything. 

Prime suspect would indeed be an issue somewhere in transpilation, or it could be in cycle.js expecting something specifically. That's about as generic as can be, I know. As a delta between the original hello world and ce-cycle, it looks like you added webpack bundling and cycle.js. 

Does the setup work with webpack without cycle.js?

**Comment by kristianmandrup** [comment]
I got it working. My bad. Making good progress with Cycle.js as well. Gitter community helped me out and pushed me forward. Thanks anyways ;)
